### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by parkourben99** [thenpingme/thenpingme-laravel#10]
When setting up a new project everything seem to go fine. I checked the dashboard and nothing was there. So I tried it again, still nothing. At this point I found the queue was not running.

I started the queue, but it showed in horizon there were two setup tasks.
This has created duplicates, this could be a issue when new pings coming in. 

![image](https://user-images.githubusercontent.com/7295774/100490744-a5ee8280-316d-11eb-8c6b-d915bdf20636.png)

I just deleted the project and created a new one to fix the issue.

Stack trace from failed ping:
```
[2020-11-28 11:04:27] production.ERROR: Undefined property: Illuminate\Http\Client\ConnectionException::$response {"exception":"[object] (ErrorException(code: 0): Undefined property: Illuminate\\Http\\Client\\ConnectionException::$response at /var/www/production.processrubber.com.au/releases/20201128105731/vendor/thenpingme/laravel/src/ThenpingmePingJob.php:41)
[stacktrace]
#0 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/thenpingme/laravel/src/ThenpingmePingJob.php(41): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Thenpingme\\ThenpingmePingJob->handle()
#2 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#6 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#7 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#8 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#10 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(403): Illuminate\\Bus\\Dispatcher->dispatchNow()
#11 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/thenpingme/laravel/src/Client/ThenpingmeClient.php(81): dispatch_now()
#12 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/thenpingme/laravel/src/Console/Commands/ThenpingmeSyncCommand.php(57): Thenpingme\\Client\\ThenpingmeClient->dispatch()
#13 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/thenpingme/laravel/src/Console/Commands/ThenpingmeSyncCommand.php(42): Thenpingme\\Console\\Commands\\ThenpingmeSyncCommand->syncTasks()
#14 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/nunomaduro/laravel-console-task/src/LaravelConsoleTaskServiceProvider.php(49): Thenpingme\\Console\\Commands\\ThenpingmeSyncCommand->Thenpingme\\Console\\Commands\\{closure}()
#15 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(114): Thenpingme\\Console\\Commands\\ThenpingmeSyncCommand->NunoMaduro\\LaravelConsoleTask\\{closure}()
#16 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/thenpingme/laravel/src/Console/Commands/ThenpingmeSyncCommand.php(43): Illuminate\\Console\\Command->__call()
#17 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Thenpingme\\Console\\Commands\\ThenpingmeSyncCommand->handle()
#18 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#20 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#22 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#23 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#24 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#25 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#26 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#27 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#28 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#29 /var/www/production.processrubber.com.au/releases/20201128105731/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#30 /var/www/production.processrubber.com.au/releases/20201128105731/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#31 {main}
```

**Comment by michaeldyrynda** [comment]
Solved by `1.3.8` and `2.3.8`, which will now dispatch the setup command in sync.
