### ISSUE TITLE
Schedule execution fails when it contains unsynchronized tasks

### ISSUE THREAD

**Issue by io238** [thenpingme/thenpingme-laravel#9]
I noticed that the execution of the app schedule (`schedule:run`) fails with a `RequestException` (404), when a new task has been added to _Kernel.php_, but has not been synced to Thenpingme yet.

I know that ideally `thenpingme:sync` should be run during deployment and then this would normally not cause any issues. In this case unfortunately, my scheduled tasks contain variables from the database, which might change after deployment. This makes the execution time of my tasks also variable.

Can you please ensure that in such cases the 404 exception will just be ignored for this new task and does not stop the execution of the rest of the scheduled tasks?

## Error Log Details
```
[2020-11-25 20:36:17] local.ERROR: HTTP request returned status code 404:
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width= (truncated...)
 {"exception":"[object] (Illuminate\\Http\\Client\\RequestException(code: 404): HTTP request returned status code 404:
<!DOCTYPE html>
<html lang=\"en\">
    <head>
        <meta charset=\"utf-8\">
        <meta name=\"viewport\" content=\"width= (truncated...)
 at ...\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\Response.php:231)
[stacktrace]
#0 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php(583): Illuminate\\Http\\Client\\Response->throw()
#1 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(263): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}(Object(Illuminate\\Http\\Client\\Response))
#2 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php(585): tap(Object(Illuminate\\Http\\Client\\Response), Object(Closure))
#3 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(234): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}(3)
#4 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php(589): retry(0, Object(Closure), 250)
#5 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php(493): Illuminate\\Http\\Client\\PendingRequest->send('POST', 'https://thenpin...', Array)
#6 ...\\vendor\\thenpingme\\laravel\\src\\ThenpingmePingJob.php(38): Illuminate\\Http\\Client\\PendingRequest->post('https://thenpin...', Array)
#7 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Thenpingme\\ThenpingmePingJob->handle()
#8 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#13 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Thenpingme\\ThenpingmePingJob))
#14 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Thenpingme\\ThenpingmePingJob))
#15 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(403): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Thenpingme\\ThenpingmePingJob), false)
#17 ...\\vendor\\thenpingme\\laravel\\src\\Client\\ThenpingmeClient.php(81): dispatch_now(Object(Thenpingme\\ThenpingmePingJob))
#18 ...\\vendor\\thenpingme\\laravel\\src\\ScheduledTaskSubscriber.php(29): Thenpingme\\Client\\ThenpingmeClient->dispatch()
#19 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(411): Thenpingme\\ScheduledTaskSubscriber->handleScheduledTaskEvent(Object(Illuminate\\Console\\Events\\ScheduledTaskStarting))
#20 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(236): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Cons...', Array)
#21 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Scheduling\\ScheduleRunCommand.php(138): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Cons...')
#22 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Scheduling\\ScheduleRunCommand.php(102): Illuminate\\Console\\Scheduling\\ScheduleRunCommand->runEvent(Object(Illuminate\\Console\\Scheduling\\CallbackEvent))
#23 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle(Object(Illuminate\\Console\\Scheduling\\Schedule), Object(Illuminate\\Events\\Dispatcher), Object(NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler))
#24 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#29 ...\\vendor\\symfony\\console\\Command\\Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 ...\\vendor\\symfony\\console\\Application.php(920): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 ...\\vendor\\symfony\\console\\Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 ...\\vendor\\symfony\\console\\Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 ...\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 {main}
"} 
```

To reproduce this, you can just add a new task to _Kernel.php_ and execute `schedule:run` without syncing the tasks before:
```
$schedule->call(function(){
          Log::info(now());
        })->description('test')->everyMinute();
```

**Comment by michaeldyrynda** [comment]
This will be fixed in 1.3.7 and 2.3.7.
